config/routes.rb
Rails.application.routes.draw do
  	resources :uploads
        
root :to => 'uploads#index'

get "/content" => "uploads#content"

get "/info" => "uploads#info"

get "/person" => "uploads#person"

get "/person_edit" => "uploads#person_edit"

post  "/edit_user" => "uploads#edit_user"

post  "/delete_user" => "uploads#delete_user"

get  "/delete_user" => "uploads#delete_user"

match "/admin_login" => "uploads#admin_login", via: [:get, :post]

match "/user_login" => "uploads#user_login", via: [:get, :post]

match "/admin_view" => "uploads#admin_view", via: [:get, :post,:patch]

post "/user_view" => "uploads#user_view"

get "/user_view" => "uploads#user_view"

get "/user_logout" => "uploads#user_logout"

get "/admin_logout" => "uploads#admin_logout"

match "/sendmail" => "uploads#sendmail", via: [:get, :post]

match "/register" => "uploads#register", via: [:get, :post]

get "/password_new" => "uploads#password_new"

get "/forgot_password" => "uploads#forgot_password"

post "/passmail" => "uploads#passmail"

get "/passmail" => "uploads#passmail"

    

end

app/models/upload.rb
class Upload
  include Mongoid::Document
  field :file, type: String
  field :filename, type: String
  field :count,type: Integer
  field :username, type: String
  validates :filename, :uniqueness =>{ :message => "  Already Exists" }
  validates :filename, :format => {:with => /$*\.(jpg|png|gif|jpeg|JPG|PNG|GIF|JPEG|doc|docx|pdf|PDF)/,:message => " must be of (jpg|png|gif|jpeg|doc|docx|pdf) extension"}

  has_many :mailids

 paginates_per 3

 mount_uploader :file, UploadFileUploader

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token
 

  # GET /uploads
  # GET /uploads.json
  def index
   @uploads1 = Upload.where( filename: /.*\.(jpeg|png|gif|jpg)/i ).order("count DESC").page params[:page_img]
   @uploads2=  Upload.where( filename: /.*\.(pdf)/i ).order("count DESC").page params[:page_pdf]
   @uploads3 = Upload.where( filename: /.*\.(doc|docx)/i ).order("count DESC").page params[:page_doc]
   @upload = Upload.new
    session[:user]= nil
    session[:pwd]= nil
  end


  def content
  @uploads1 = Upload.where( filename: /.*\.(jpeg|png|gif|jpg)/i ).order("count DESC").page params[:page_img]
  @uploads2=  Upload.where( filename: /.*\.(pdf)/i ).order("count DESC").page params[:page_pdf]
  @uploads3 = Upload.where( filename: /.*\.(doc|docx)/i ).order("count DESC").page params[:page_doc]
  @upload = Upload.new
  @credentials=People.all
  end




  # GET /uploads/new
  def new
    @upload = Upload.new
  end




  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end



  def person
    @people = People.new
  end



  def register
    @uname=params[:people][:username]
    @pass=params[:people][:password]
    @name=params[:people][:name]
    @email=params[:people][:email]
    @people = People.new(:username => @uname,:password => @pass,:name=> @name,:email => @email)
    if @people.save
     respond_to do |format|
       format.html { redirect_to user_login_path,notice: 'Registered Successfully'}
     end
    else
      respond_to do |format|
       format.html { redirect_to person_path,notice: 'Username Already exists'}
     end
    end 
   end



  def admin_login
    session[:user]= nil
    session[:pwd]= nil
    @login =Login.new
  end 

  def admin_logout
    session[:user]= nil
    session[:pwd]= nil
    redirect_to root_path
  end 

  def user_logout
    session[:user]= nil
    session[:pwd]= nil
    redirect_to root_path
  end 

  def user_login
    session[:user]= nil
    session[:pwd]= nil
    @login = Login.new
   

  end 



  def admin_view
    
    @creds=Login.all
    @creds.each do |cred| 
      @un=cred.username
      @pw=cred.password
    end
     
    begin
      if ((session[:user]==nil) and (session[:pwd]== nil))
          session[:user]=params[:login][:username]
          session[:pwd]= params[:login][:password]
        end
     
      if @un == session[:user] and @pw == session[:pwd]
        
      else
        respond_to do |format|
          format.html { redirect_to "/admin_login" ,notice: 'Invalid Credentials'}
        end
      end
    rescue  
        respond_to do |format|
          format.html { redirect_to "/admin_login" }
        end
    end    

  end





  def user_view

    @val=params[:check1]

 

    @credentials=People.all
    @check=0
 begin
    @credentials.each do |cred| 
        @un1=cred.username
        @pw1=cred.password
        if ((session[:user]==nil) and (session[:pwd]== nil))
          session[:user]=params[:login][:username]
          session[:pwd]= params[:login][:password]
        end
       
      if @un1 == session[:user] and @pw1  == session[:pwd]
       @check=@check+1
         if params[:check1] == "1"
         cookies.signed[:username] = { :value => params[:login][:username], :expires => 2.weeks.from_now }
         cookies.signed[:password] = { :value => params[:login][:password], :expires => 2.weeks.from_now }
        end

      end
    end
    if @check == 0 
      respond_to do |format|
          format.html { redirect_to "/user_login",notice: 'Invalid Credentials' }
        end
    end
   rescue
     respond_to do |format|
          format.html { redirect_to "/user_login" }
        end
   end

end



  def info
  @credentials=People.all.page params[:page]
  @uploads1 = Upload.where( filename: /.*\.(jpeg|png|gif|jpg)/i ).order("count DESC").page params[:page_img]
  @uploads2=  Upload.where( filename: /.*\.(pdf)/i ).order("count DESC").page params[:page_pdf]
  @uploads3 = Upload.where( filename: /.*\.(doc|docx)/i ).order("count DESC").page params[:page_doc]
  end




  def sendmail
    
    @email_user = params[:email]
    @subject = params[:body]
    @src = params[:src]
    @mail=params[:email]
    @id=params[:idref]
    @email = Mailid.new(:mail => @mail,:upload_id => @id)
    @email.save
    @upload = Upload.find(@id)
    @upload.update_attributes(:count => ((@upload.count.nil? ? 0 : @upload.count) + @email.mail.split(",").size) )
    UserMailer.welcome_mail(@email_user,@subject,@src).deliver
      respond_to do |format|
        format.html { redirect_to uploads_url, :notice => "Mail was successfully sent to #{@email_user}" }
      end
  end

 
  def forgot_password
   
    @people=People.new

  end

  def passmail

    begin
     @usn=params[:people][:name]
     @det=People.where(:username => @usn)
     
     @det.each do |cred| 
         @pws=cred.password
         @pmail=cred.email
      end
    UserMailer.pass_mail(@pmail,@pws).deliver
    respond_to do |format|
        format.html { redirect_to user_login_path ,:notice => "Password was successfully sent to #{@pmail}"}
      end
    rescue
       respond_to do |format|
        format.html { redirect_to forgot_password_path ,:notice => "Enter Valid Username"}
      end
    end

  end



 

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @fn=params[:upload][:file].original_filename
    @upload = Upload.new(upload_params)
    @unm=session[:user]
    @upload.update(:filename => @fn,:username => @unm)
    @uploads = Upload.all

    respond_to do |format|
      if @upload.save
        format.html { redirect_to user_view_path, notice: 'Upload was successfully created.' }
        format.json { render :show, status: :created, location: @upload }
      else
        format.html { redirect_to user_view_path}
        format.js
      end
    end
  end



  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload.destroy
    
  end

  def delete_user
   People.where(:username => params[:uname]).delete
   respond_to do |format|
          format.html { redirect_to "/info" }
        end
  end


  def person_edit
    
    @unam=params[:unam]
    @fname=params[:fname]
    @umail=params[:umail]
    @people=People.new
  
  end


   
  def edit_user
     
    People.where(:username => params[:people][:unam]).update( :name => params[:people][:name],:email => params[:people][:email])
    respond_to do |format|
          format.html { redirect_to "/admin_view" }
     end

  end





  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end






  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params.require(:upload).permit(:file, :mailid)
    end



end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_credents.html.erb
<% @credentials.each do |upload| %>
        
    <table>
       <tr>


            <td class="name"  id ="uname">
                <%= upload.username %>
            </td>

            <td class="name" >
                <%= upload.password %>
            </td>

            <td class="name" id ="fname">
                <%= upload.name %>
            </td>

            <td class="name" id ="umail">
                <%= upload.email %>
            </td>

           <td class="name">
             <%= link_to 'Delete', "#" ,:remote => true, :id => "delete_user" %>
           </td>

           <td class="name">
             <%= link_to 'Edit', "/person_edit?unam=#{upload.username}&fname=#{upload.name}&umail=#{upload.email}", :id => "edit_user" %>
           </td>
        </tr>  
    </table>
<% end %>

app/views/uploads/_uploads11.html.erb
<% @uploads1.each do |upload| %>
      <% if upload.filename =~ /^.*\.(jpg|png|gif|jpeg|JPG|PNG|GIF|JPEG)$/ %>
      
      <table>
      <tr>
          <td>
   
          <%= link_to image_tag("#{upload.file}",:class => 'lightbox_trigger11',:width => "50px",:height => "50px",:id => "#{upload.id}"), '#' %>
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td class="name">
          <%= upload.filename %>
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <% if session[:user]==upload.username %>
          <td>
          <%= link_to 'Delete', upload, method: :delete ,:class => "del1",:remote => true  %>
          </td>
          <% end %>
   
          

      </tr>
      </table>
     <% end %>
<% end %> 

app/views/uploads/_uploads22.html.erb
<% @uploads2.each do |upload| %>
    <% if upload.filename =~ /^.*\.(pdf|PDF)$/ %>
      <table>
      <tr>
          <td>
          <%= link_to image_tag("/assets/pdf.png",:width => "50px",:height => "50px"), "/#{upload.file}",:class => 'lightbox_trigger22',:id => "#{upload.id}" %>
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td class="name">
          <%= upload.filename %>
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <% if session[:user]==upload.username %>
          <td>
          <%= link_to 'Delete', upload, method: :delete,:class => "del1" ,:remote => true %>
          </td>
          <% end %>
    
      </tr>
      </table>
   <% end %> 
<% end %> 

app/views/uploads/_uploads33.html.erb
<% @uploads3.each do |upload| %>
   <% if upload.filename =~ /^.*\.(doc|docx)$/ %>
      <table>
      <tr>
          <td>
          <%= link_to image_tag("/assets/microw.png",:width => "50px",:height => "50px"),  "/#{upload.file}" ,:class => 'lightbox_trigger33' ,:id => "#{upload.id}" %>
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td class="name">
          <%= upload.filename %>
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <% if session[:user]==upload.username %>
          <td>
          <%= link_to 'Delete', upload, method: :delete,:class => "del1",:remote => true %>
          </td>
        <% end %>
      </tr>
      </table>  
   <% end %>  
<% end %>  

app/views/uploads/admin_login.html.erb
<head>
<style>
body
{
  padding: 0px;
  margin:0 auto;
  background-color:#778899;
}
#cred
{
     width:400px;
     height:250px;
     border:10px solid #000;
     margin-left:350px;
     margin-top:100px;
    
     border-radius:10px;
     background-color:#DDDDD5;
}
.field
{
    margin-top: 40px;
    margin-left:50px;
     font-size: 15px;
}
.field1
{
    margin-top: 10px;
    margin-left:50px;
    font-size: 15px;
}
.actions
{
    margin-top:20px;
    margin-left:150px;
}
#mh
{
   margin-left:400px;
   color:#fff;
   font-family:verdana;
   font-size: 35px;
   margin-top:100px;
}
#back
{

  margin-top:40px;
  
}
#notice
{
  font-size: 15px;
}

.admin
{
    font-size:20px;
    font-family:verdana;
    float:right;
    margin-right:30px;
    padding-top:30px;
    text-decoration: none;
}
   
</style>
</head>

<%= form_for(@login,:url => { :action => :admin_view}) do |f| %>

<h1 id="mh">Admin login</h1>

<%= link_to "Home Page" ,root_path,:class => "admin" %>

<div id="cred">
 

   <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username,:required => true %>
   </div>
   <div class="field1">
    <%= f.label :password %>
    <%= f.password_field :password,:required => true%>
    </div>
   
   

   <div class="actions">
    <%= f.submit :Login %>

    <p id="notice"><%= notice %></p>

   </div>

</div>

<% end %>

app/views/uploads/admin_view.html.erb
<script>
function remove1()
{
  document.getElementById("lightbox").remove();
}


$(function(){
 $.ajax({
  url: '/info',
  type: 'GET',
  success: function(data) {
        $("#media").html(data);
  }
});

});







</script>
<style>
.hed
{
    margin-left:20px;
    font-size: 15px;
    color: #E19063;

}

#lightbox 
{
    position:fixed; 
    top:0;
    left:0;
    width:100%;
    height:100%;
    background-color:#778899;
    opacity:1.0;
    text-align:center;
 }
 #lightbox img 
{
     box-shadow:0 0 25px #111;
    -webkit-box-shadow:0 0 25px #111;
    -moz-box-shadow:0 0 25px #111;
     max-width:540px;
     max-height:800px;
  
}
body
{
  padding: 0px;
  margin:0 auto;
}

#main
{
  background-color:#E6E7E8;
    height:80px;
}
.admin
{
    font-size:20px;
    font-family:verdana;
    float:right;
    margin-right:30px;
    padding-top:30px;
    text-decoration: none;
}
#img1
{
  border:15px solid;
}

.mainhead
{
  font-size:25px;
  padding-top:30px;
  margin-left:350px;
  font-color:#FE646A;
}


.userhead
{
  font-size:25px;
  padding-top:30px;
  margin-left:400px;
  font-color:#FE646A;
}
.name
{
  padding-left:40px;
  width:150px;
  font-size:17px;
}

.head
{
  padding-left:40px;
  width:150px;
  font-size:15px;
  color: blue;
}


.del1
{
    position:relative;
    font-size:15px;
    text-decoration: none;
    padding-left:20px;
}

.mail
{
  display:none;
  font-size:14px;
}
#mails
{
  color:#FFFFFF;
  font-size:20px;
}

#media
{
  margin:0 auto; 
    margin-top:50px;
    width:100%;
    height:1000px;
    background-color:#E6E7E8;
}
#imgs
{

    width:30%;
    margin:0 auto; 
    background:#DDDDD5;
    text-align:left; 
    border:5px solid #000;
    padding:10px;
    float:left;
     margin-left: 20px;
   
}
#pdfs
{
    width:30%;
    margin:0 auto;
    background:#DDDDD5;
    text-align:left;
    border:5px solid #000;
    padding:10px;
    float:left;
    margin-left: 20px;
   
}
#docs
{
    width:27%;
    margin:0 auto; 
    background:#DDDDD5;
    text-align:left; 
    border:5px solid #000;
    padding:10px;
    float:left;
    margin-left: 20px;

}

.pagination
{
  float:right;
  font-size:14px;
  margin-right:100px;
}

#btn
{
   margin-left:700px;
   margin-top:40px;
}


</style>

  <div id="main">
    <%= link_to "Logout" ,admin_logout_path,:class => "admin" %>
    <h1 class="mainhead">Welcome To DashBoard</h1>
  </div>

<div id="media">


</div>


<div id="script1">
<%= render :partial =>'script' %>
</div>

app/views/uploads/content.html.erb
<br>
<br>
<div id="fo">
<%= render 'form' %>
</div>

<br>
<br>



<div id="imgs">
<h1 class="hed">Uploaded Images</h1>
<div id="uploads11">
<%= render 'uploads11' %>
</div>
<div id="paginator11">
<%= paginate @uploads1,:param_name => "page_img" ,:remote => true %> 
</div>
</div>


     
<div id="pdfs">
<h1 class="hed">Uploaded PDF files</h1>

<div id="uploads22">
<%= render 'uploads22' %>
</div>
<div id="paginator22">
<%= paginate @uploads2,:param_name => "page_img" ,:remote => true %> 
</div>
</div>    
     


<div id="docs">
<h1 class="hed">Uploaded Word Documents</h1>

<div id="uploads33">
<%= render 'uploads33' %>
</div>
<div id="paginator33">
<%= paginate @uploads3,:param_name => "page_img" ,:remote => true %> 
</div>
</div>

app/views/uploads/content.js.erb
$('#uploads11').html('<%= escape_javascript(render("uploads11")) %>');
$('#uploads22').html('<%= escape_javascript(render("uploads22")) %>');
$('#uploads33').html('<%= escape_javascript(render("uploads33")) %>');


$('#paginator11').html('<%= escape_javascript(paginate(@uploads1,:param_name => "page_img",:remote => true).to_s) %>');
$('#paginator22').html('<%= escape_javascript(paginate(@uploads2,:param_name => "page_pdf", :remote => true).to_s) %>');
$('#paginator33').html('<%= escape_javascript(paginate(@uploads3,:param_name => "page_doc",:remote => true).to_s) %>');
$('#script2').html('<%= escape_javascript(render("script")) %>');

app/views/uploads/create.js.erb
$.ajax({
        url: "/content",
        type: 'GET',
        success: function(data) {
              $("#wrappers").html(data);
        }
    });

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/info.html.erb
 
 <h1 class="userhead">Users List</h1>


 <table>
       <tr>  
              

            <td class="head">
                <%= "Username" %>
            </td>

            <td class="head">
                <%= "Password" %>
            </td>

            <td class="head">
                <%= "Name" %>
            </td>

            <td class="head">
                <%= "Email" %>
            </td>

           
        </tr>  
    </table>





<div id="credents">
<%= render 'credents' %>
</div>
<div id="paginator">
<%= paginate @credentials,:remote => true %> 
</div>

<br>
<br>


<br>
<br>


<div id="imgs">
<h1 class="hed">Uploaded Images</h1>
<div id="uploads1">
<%= render 'uploads1' %>
</div>
<div id="paginator1">
<%= paginate @uploads1,:param_name => "page_img" ,:remote => true %> 
</div>
</div>


     
<div id="pdfs">
<h1 class="hed">Uploaded PDF files</h1>
<div id="uploads2">
 <%= render 'uploads2' %>
 </div>
<div id="paginator2">
 <%= paginate @uploads2,:param_name => "page_pdf",:remote => true %> 
 </div>
</div>    
     


<div id="docs">
<h1 class="hed">Uploaded Word Documents</h1>
<div id="uploads3">
<%= render 'uploads3' %>
</div>
<div id="paginator3">
<%= paginate @uploads3,:param_name => "page_doc",:remote => true %> 
</div>
</div>
  
</div>








   

app/views/uploads/new.html.erb
<style>
.back
{
	font-size: 20px;
	margin-left: 100px;
}
#error
{
	margin-top:100px;
}
</style>

<div id="error">
<%= render 'form' %>
</div>

<%= link_to 'Back', uploads_path,:class => "back" %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File:</strong>
  <%= @upload.file %>
</p>

<p>
  <strong>Mailid:</strong>
  <%= @upload.mailid %>
</p>

<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/user_view.html.erb
<head>
<script>


$(function(){
$.ajax({
  url: '/content',
  type: 'GET',
  success: function(data) {
        $("#wrappers").html(data);
  }
});

});






function remove1()
{
  document.getElementById("lightbox").remove();
}
function load()
{
  var em=document.getElementById("mail").value;
    if(em==null || em=="")
  {
    document.getElementById("loading").style.display="none";
  }
  
  else
  {
    document.getElementById("loading").style.display="inline";
  }

}

</script>

<style>
#lightbox img 
{
     box-shadow:0 0 25px #111;
    -webkit-box-shadow:0 0 25px #111;
    -moz-box-shadow:0 0 25px #111;
     max-width:540px;
     max-height:800px;
  
}
body
{
  padding: 0px;
  margin:0 auto;
}
#img1
{
  border:15px solid;
}

#lightbox 
{
    position:fixed; /* keeps the lightbox window in the current viewport */
    top:0;
    left:0;
    width:100%;
    height:100%;
    background-color:#778899;
    opacity:1.0;
    text-align:center;
}
#btn
{
   margin-left:700px;
   margin-top:40px;
}
#wrapper
{
    width:100%;
    margin:0 auto; /*centers the div horizontally in all browsers (except IE)*/
    background:#525A73;
    text-align:left; /*resets text alignment from body tag */
    padding:25px;
    height: 1000px;

    
    /*Let's add some CSS3 styles, these will degrade gracefully in older browser and IE*/
   
}
embed
{
  height:800px;
  width:1000px;
}
.mhed
{
    margin-left:400px;
    font-size:35px;
    color:#F5F5F5;
    font-family:verdana;
    text-shadow: 15px 15px 15px #000;

}
.admin
{
   
    font-size:25px;
    font-family:verdana;
    float:right;
    margin-right:40px;

}
.user
{
   
    font-size:25px;
    font-family:verdana;
    margin-left:40px;

}
.hed
{
    margin-left:20px;
    font-size: 15px;
    color: #E19063;

}
.del
{
    position:relative;
    font-size:15px;
    text-decoration: none;
}
#new 
{
   
    font-size:25px;
    color:#fff;
    text-decoration: none;
    border:5px solid;
    
}

#imgs
{

    width:27%;
    margin:0 auto; /*centers the div horizontally in all browsers (except IE)*/
    background:#DDDDD5;
    text-align:left; /*resets text alignment from body tag */
    border:5px solid #000;
    padding:10px;
    float:left;
  box-shadow: 10px 10px 5px #000;
}
#pdfs
{
    width:27%;
    margin:0 auto; /*centers the div horizontally in all browsers (except IE)*/
    background:#DDDDD5;
    text-align:left; /*resets text alignment from body tag */
    border:5px solid #000;
    padding:10px;
    float:left;
    margin-left: 20px;
  box-shadow: 10px 10px 5px #000;
}
#docs
{
    width:27%;
    margin:0 auto; /*centers the div horizontally in all browsers (except IE)*/
    background:#DDDDD5;
    text-align:left; /*resets text alignment from body tag */
    border:5px solid #000;
    padding:10px;
    float:left;
    margin-left: 20px;
    box-shadow: 10px 10px 5px #000;
}
p
{
   font-size: 20px;
   color: #F5F5F5;
}
.name
{
  width:150px;
}
#notice
{
  
  font-size: 15px;
}
#close
{

  width:50px;
  height:50px;
}
#mesg
{
  width:450px;

}
#uhead
{

    font-size:25px;
    color:#87CEFA;
    font-family:verdana;
    text-shadow: 15px 15px 15px #000;
}

</style>

</head>



<div id="wrapper">


<h1 class="mhed">File Upload Gallery</h1>



<div>

<%= link_to "Logout", user_logout_path ,:class => "admin" %>

</div>
<h1 id="uhead">Welcome <%= session[:user] %></h1>
<div id="wrappers">
</div>

</div>



<div id="script2">
  <%= render :partial => 'script' %>
</div>